platform_umbrella/apps/home_base_web/lib/home_base_web/router.ex
defmodule HomeBaseWeb.Router do
  use HomeBaseWeb, :router

  import HomeBaseWeb.RequestURL
  import HomeBaseWeb.UserAuth

  @redirect_authenticated_user {HomeBaseWeb.UserAuth, :redirect_authenticated_user}
  @ensure_authenticated_user {HomeBaseWeb.UserAuth, :ensure_authenticated}
  @mount_current_user {HomeBaseWeb.UserAuth, :mount_current_user}

  @root_layout {HomeBaseWeb.Layouts, :root}
  @auth_layout {HomeBaseWeb.Layouts, :auth}
  @app_layout {HomeBaseWeb.Layouts, :app}

  pipeline :auth_layout, do: plug(:put_layout, html: @auth_layout)
  pipeline :app_layout, do: plug(:put_layout, html: @app_layout)

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_current_user
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, html: @root_layout
    plug :put_layout, false
    plug :assign_request_info
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Enum.member?([:dev, :test], Mix.env()) do
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
      live_dashboard "/dashboard", metrics: HomeBaseWeb.Telemetry
    end
  end

  scope "/", HomeBaseWeb do
    pipe_through :browser

    delete "/logout", UserSessionController, :delete
  end

  scope "/", HomeBaseWeb do
    pipe_through [:browser, :auth_layout]

    live_session :confirm, layout: @auth_layout, on_mount: [@mount_current_user] do
      live "/confirm/:token", ConfirmLive
    end
  end

  scope "/", HomeBaseWeb do
    pipe_through [:browser, :auth_layout, :redirect_authenticated_user]

    post "/login", UserSessionController, :create

    live_session :auth, layout: @auth_layout, on_mount: [@redirect_authenticated_user] do
      live "/signup", SignupLive
      live "/login", LoginLive
      live "/reset", ForgotPasswordLive
      live "/reset/:token", ResetPasswordLive
    end
  end

  scope "/", HomeBaseWeb do
    pipe_through [:browser, :app_layout, :require_authenticated_user]

    live_session :app, layout: @app_layout, on_mount: [@ensure_authenticated_user] do
      live "/", DashboardLive

      live "/installations/", InstallationLive
      live "/installations/new", InstallationNewLive
      live "/installations/:id", InstallationShowLive, :show
      live "/installations/:id/success", InstallationShowLive, :success
      live "/installations/:id/edit", InstallationEditLive

      live "/teams/new", TeamsNewLive

      live "/settings", SettingsLive
      live "/settings/:token", SettingsLive

      live "/help", HelpLive
    end

    get "/teams/:id", TeamsController, :switch
  end

  scope "/api/v1/", HomeBaseWeb do
    pipe_through :api

    get "/stable_versions", StableVersionsController, :show

    scope "/installations/:installation_id" do
      resources "/usage_reports", StoredUsageReportController, only: [:create]
      resources "/host_reports", StoredHostReportController, only: [:create]
      resources "/project_snapshots", StoredProjectSnapshotController, only: [:create, :index]
      get "/status", InstallationStatusContoller, :show
      get "/spec", InstallSpecController, :show
      get "/script", InstallScriptController, :show
    end
  end

  scope "/admin/", HomeBaseWeb do
    pipe_through [:browser, :app_layout, :require_authenticated_user, :require_admin_user]

    # TODO: Change this to ensure_admin_team_user
    live_session :admin, layout: @app_layout, on_mount: [@ensure_authenticated_user] do
      live "/teams", Live.Admin.TeamsIndex, :index
      live "/teams/:id", Live.Admin.TeamsShow, :show

      live "/installations", Live.Admin.InstallationsIndex, :index
      live "/installations/:id", Live.Admin.InstallationsShow, :show
      live "/users", Live.Admin.UsersIndex, :index
      live "/users/:id", Live.Admin.UsersShow, :show
    end
  end
end

platform_umbrella/apps/home_base_web/lib/home_base_web/live/admin/installations/index.ex
defmodule HomeBaseWeb.Live.Admin.InstallationsIndex do
  @moduledoc false

  use HomeBaseWeb, :live_view

  import HomeBaseWeb.Admin.InstallationsTable

  alias HomeBase.CustomerInstalls

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :page_title, "Installations")}
  end

  def handle_params(_params, _session, socket) do
    {:noreply, assign(socket, :installations, CustomerInstalls.list_installations())}
  end

  def render(assigns) do
    ~H"""
    <.flex column>
      <.panel title="All Installations">
        <.installations_table rows={@installations} />
      </.panel>
    </.flex>
    """
  end
end

platform_umbrella/apps/home_base_web/lib/home_base_web/live/admin/installations/show.ex
defmodule HomeBaseWeb.Live.Admin.InstallationsShow do
  @moduledoc false

  use HomeBaseWeb, :live_view

  import HomeBaseWeb.Admin.UsageReportsTable

  alias HomeBase.CustomerInstalls
  alias HomeBase.ET

  def mount(%{"id" => id}, _session, socket) do
    installation = CustomerInstalls.get_installation!(id)
    usage_reports = ET.list_recent_usage_reports(installation)
    host_report = ET.get_most_recent_host_report(installation)

    {:ok,
     socket
     |> assign(:installation, installation)
     |> assign(:usage_reports, usage_reports)
     |> assign(:host_report, host_report)}
  end

  def render(assigns) do
    ~H"""
    <.grid columns={%{sm: 1, lg: 2}}>
      <.panel title="Installation">
        <.data_list>
          <:item title="ID">{@installation.id}</:item>
          <:item title="Slug">{@installation.slug}</:item>
          <:item :if={@installation.team} title="Team">
            <.a navigate={~p"/admin/teams/#{@installation.team.id}/"} variant="underlined">
              {@installation.team.name}
            </.a>
          </:item>
          <:item title="User">
            <.a
              :if={@installation.user}
              navigate={~p"/admin/users/#{@installation.user.id}/"}
              variant="underlined"
            >
              {@installation.user.email}
            </.a>
            <div :if={@installation.user == nil}>Only owned by Team</div>
          </:item>
        </.data_list>
      </.panel>
      <.panel title="Hosts">
        <.data_list :if={@host_report && @host_report.report}>
          <:item title="Control Server Host">
            {@host_report.report.control_server_host}
          </:item>
        </.data_list>
      </.panel>
      <.panel title="Usage Reports" class="lg:col-span-2">
        <.usage_reports_table rows={@usage_reports} />
      </.panel>
    </.grid>
    """
  end
end

platform_umbrella/apps/home_base_web/lib/home_base_web/live/admin/teams/index.ex
defmodule HomeBaseWeb.Live.Admin.TeamsIndex do
  @moduledoc false

  use HomeBaseWeb, :live_view

  import HomeBaseWeb.Admin.TeamsTable

  alias HomeBase.Teams

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :page_title, "Teams")}
  end

  def handle_params(_params, _session, socket) do
    {:noreply, assign(socket, :teams, Teams.list_teams())}
  end

  def render(assigns) do
    ~H"""
    <.flex column>
      <.panel title="All Teams">
        <.teams_table rows={@teams} />
      </.panel>
    </.flex>
    """
  end
end

platform_umbrella/apps/home_base_web/lib/home_base_web/live/admin/teams/show.ex
defmodule HomeBaseWeb.Live.Admin.TeamsShow do
  @moduledoc false

  use HomeBaseWeb, :live_view

  import HomeBaseWeb.Admin.InstallationsTable
  import HomeBaseWeb.Admin.UsersTable

  alias HomeBase.Teams

  def mount(%{"id" => id}, _session, socket) do
    team = Teams.get_team!(id)

    {:ok, assign(socket, :team, team)}
  end

  def render(assigns) do
    ~H"""
    <.grid columns={%{sm: 1, lg: 2}}>
      <.panel title="Team">
        <.data_list>
          <:item title="ID">{@team.id}</:item>
          <:item title="Name">{@team.name}</:item>
        </.data_list>
      </.panel>
      <.panel title="Users">
        <.users_table rows={@team.users} />
      </.panel>

      <.panel title="Installations" class="lg:col-span-2">
        <.installations_table rows={@team.installations} />
      </.panel>
    </.grid>
    """
  end
end

platform_umbrella/apps/home_base_web/lib/home_base_web/live/admin/users/index.ex
defmodule HomeBaseWeb.Live.Admin.UsersIndex do
  @moduledoc false
  use HomeBaseWeb, :live_view

  import HomeBaseWeb.Admin.UsersTable

  alias HomeBase.Accounts

  def mount(_params, _session, socket) do
    {:ok, assign(socket, :page_title, "Users")}
  end

  def handle_params(_params, _session, socket) do
    {:noreply, assign(socket, :users, Accounts.list_users())}
  end

  def render(assigns) do
    ~H"""
    <.flex column>
      <.panel title="All Users">
        <.users_table rows={@users} />
      </.panel>
    </.flex>
    """
  end
end

platform_umbrella/apps/home_base_web/lib/home_base_web/live/admin/users/show.ex
defmodule HomeBaseWeb.Live.Admin.UsersShow do
  @moduledoc false

  use HomeBaseWeb, :live_view

  import HomeBaseWeb.Admin.TeamsTable

  alias HomeBase.Accounts

  def mount(%{"id" => id}, _session, socket) do
    user = Accounts.get_user!(id)

    {:ok, assign(socket, :user, user)}
  end

  def render(assigns) do
    ~H"""
    <.grid columns={%{sm: 1, lg: 2}}>
      <.panel title="User">
        <.data_list>
          <:item title="ID">{@user.id}</:item>
          <:item title="email">{@user.email}</:item>
          <:item title="Confirmed at">{@user.confirmed_at}</:item>
        </.data_list>
      </.panel>
      <.panel title="Teams">
        <.teams_table rows={@user.teams} />
      </.panel>
      <.panel title="Installations" class="lg:col-span-2"></.panel>
    </.grid>
    """
  end
end

platform_umbrella/apps/home_base_web/lib/home_base_web/live/confirm_live.ex
defmodule HomeBaseWeb.ConfirmLive do
  @moduledoc false
  use HomeBaseWeb, :live_view

  alias HomeBase.Accounts

  def mount(%{"token" => token}, _session, socket) do
    {:ok,
     socket
     |> assign(:token, token)
     |> assign(:page_title, "Confirm your account")}
  end

  def handle_event("confirm", _params, socket) do
    case Accounts.confirm_user(socket.assigns.token) do
      {:ok, _} ->
        # Do not log in the user after confirmation to avoid a
        # leaked token giving the user access to the account.
        if socket.assigns.current_user do
          {:noreply,
           socket
           |> put_flash(:global_success, "User confirmed successfully")
           |> redirect(to: ~p"/")}
        else
          {:noreply,
           socket
           |> put_flash(:success, "User confirmed successfully")
           |> redirect(to: ~p"/login")}
        end

      :error ->
        # If there is a current user and the account was already confirmed,
        # then odds are that the confirmation link was already visited, either
        # by some automation or by the user themselves, so we redirect without
        # a warning message.
        case socket.assigns.current_user do
          %{confirmed_at: confirmed_at} when not is_nil(confirmed_at) ->
            {:noreply, redirect(socket, to: ~p"/")}

          nil ->
            {:noreply,
             socket
             |> put_flash(:error, "Link is invalid or it has expired")
             |> redirect(to: ~p"/login")}
        end
    end
  end

  def render(assigns) do
    ~H"""
    <.panel variant="shadowed" title="Confirm your account" title_size="lg">
      <p class="mb-8">
        Thanks for signing up with Batteries Included, we're so excited to have you here!
        Please take a moment to confirm your email address by clicking on the button below.
      </p>

      <.button
        variant="primary"
        class="w-full"
        icon={:check_circle}
        icon_position={:right}
        phx-click="confirm"
      >
        Confirm your account
      </.button>
    </.panel>
    """
  end
end

platform_umbrella/apps/home_base_web/lib/home_base_web/live/dashboard_live.ex
defmodule HomeBaseWeb.DashboardLive do
  @moduledoc false
  use HomeBaseWeb, :live_view

  alias CommonCore.Installation
  alias HomeBase.Accounts
  alias HomeBase.CustomerInstalls

  on_mount {HomeBaseWeb.RequestURL, :default}

  def mount(_params, _session, socket) do
    total_teams = CustomerInstalls.count_teams(socket.assigns.current_user)
    total_installations = CustomerInstalls.count_installations(socket.assigns.current_user)
    recent_installations = CustomerInstalls.list_recent_installations(socket.assigns.current_user)

    {:ok,
     socket
     |> assign(:page, :dashboard)
     |> assign(:page_title, "Dashboard")
     |> assign(:total_teams, total_teams)
     |> assign(:total_installations, total_installations)
     |> assign(:recent_installations, recent_installations)
     |> assign(:confirmation_resent, false)}
  end

  def handle_event("resend_confirm", _params, socket) do
    user = socket.assigns.current_user

    with {:ok, token} <- Accounts.get_user_confirmation_token(user),
         {:ok, _} <-
           %{to: user.email, url: socket.assigns.request_url <> ~p"/confirm/#{token}"}
           |> HomeBaseWeb.ConfirmEmail.render()
           |> HomeBase.Mailer.deliver() do
      {:noreply, assign(socket, :confirmation_resent, true)}
    else
      _ -> {:noreply, put_flash(socket, :global_error, "Could not resend confirmation email")}
    end
  end

  def render(assigns) do
    ~H"""
    <div class="flex flex-wrap items-center justify-between gap-4 mb-4 lg:mb-6">
      <div class="flex flex-wrap gap-4">
        <.badge label="Teams" value={@total_teams} />
        <.badge label="Installations" value={@total_installations} />
      </div>
    </div>

    <.grid columns={[sm: 1, md: 2, lg: 3]}>
      <.panel :if={@total_installations <= 0} title="First Steps">
        <p class="mb-6">
          Welcome to Batteries Included! Ready to get started with a new installation? You can run it on your local machine or on a Kubernetes cluster.
        </p>

        <.button variant="primary" link={~p"/installations/new"}>Create an installation</.button>
      </.panel>

      <.panel :if={@current_user.roles == []} title="Working with others?">
        <p class="mb-6">
          Create a team that others can be invited to as an admin or member. Each person can see and manage the team's installations, and each team is billed individually.
        </p>

        <.button variant="secondary" link={~p"/teams/new"}>
          Create a team
        </.button>
      </.panel>

      <.panel :if={!@current_user.confirmed_at} title="Confirm Your Account">
        <p class="mb-6">
          Your account still needs to be been confirmed. Please check your email for a confirmation link.
        </p>

        <.button disabled={@confirmation_resent} variant="secondary" phx-click="resend_confirm">
          {if @confirmation_resent, do: "Sent!", else: "Resend Confirmation Link"}
        </.button>
      </.panel>

      <.panel :if={@total_installations > 0} title="Recent Installations">
        <.table
          id="recent-installations"
          rows={@recent_installations}
          row_click={&JS.navigate(show_installation_url(&1))}
        >
          <:col :let={installation} label="Slug">{installation.slug}</:col>
          <:col :let={installation} label="Team">
            {if installation.team, do: installation.team.name, else: "Personal"}
          </:col>

          <:action :let={installation}>
            <.button
              variant="minimal"
              link={~p"/installations/#{installation}"}
              icon={:eye}
              id={"show_installation_" <> installation.id}
            />

            <.tooltip target_id={"show_installation_" <> installation.id}>
              Show Installation
            </.tooltip>
          </:action>
        </.table>
      </.panel>

      <.panel :if={@total_installations > 0} title="Keep Going">
        <p class="mb-6">
          Are you ready to expand your infrastructure even more? Get started with another installation and keep this thing going.
        </p>

        <.button variant="secondary" link={~p"/installations/new"}>Create a new installation</.button>
      </.panel>
    </.grid>
    """
  end

  defp show_installation_url(%Installation{} = installation) do
    ~p"/teams/#{installation.team_id || "personal"}?redirect_to=/installations/#{installation.id}"
  end
end

platform_umbrella/apps/home_base_web/lib/home_base_web/live/installation/show.ex
defmodule HomeBaseWeb.Live.InstallatitonShow do
  @moduledoc false
  use HomeBaseWeb, :live_view

  alias HomeBase.CustomerInstalls

  @impl Phoenix.LiveView
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl Phoenix.LiveView
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:installation, CustomerInstalls.get_installation!(id))}
  end

  defp page_title(:show), do: "Show Installation"

  @impl Phoenix.LiveView
  def render(assigns) do
    ~H"""
    <.data_list>
      <:item title="Slug"><%= @installation.slug %></:item>
    </.data_list>

    <.a navigate={~p"/installations/#{@installation}/show"}>
      <.button variant="secondary">Edit installation</.button>
    </.a>
    """
  end
end

platform_umbrella/apps/home_base_web/lib/home_base_web/live/billing_report_live/index.html.leex
<h1 class="flex-1 text-2xl font-bold text-gray-900 pb-6">
  Listing Billing reports
</h1>

<div class="shadow border-b border-gray-100 rounded-lg">
  <table class="min-w-full divide-y divide-gray-300">
    <thead class="bg-gray-200">
      <tr>
        <th
          class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
        >
          Start
        </th>
        <th
          class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
        >
          End
        </th>
        <th
          class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
        >
          Total node hours
        </th>
        <th
          class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
        >
          Total pod hours
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody id="billing_reports">
      <%= for billing_report <- @billing_reports do %>
        <tr id="billing_report-<%= billing_report.id %>">
          <td><%= billing_report.start %></td>
          <td><%= billing_report.end %></td>
          <td><%= billing_report.node_hours %></td>
          <td><%= billing_report.pod_hours %></td>

          <td>
            <span><%= live_redirect "Show", to: Routes.billing_report_show_path(@socket, :show, billing_report) %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<button
  type="button"
  phx-click="start_billing"
  class="inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-base font-medium rounded-md text-pink-900 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
>
  Generate Next Billing
</button>

platform_umbrella/apps/home_base_web/lib/home_base_web/live/billing_report_live/show.html.leex
<div class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6">
    <h1 class="text-xl leading-6 font-medium text-gray-800">Billing Report</h1>
  </div>
  <div class="border-t border-gray-200 px-4 py-5 sm:px-0">
    <dl class="sm-divide-y sm:divide-gray-200">
      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Start Date/Time</dt>
        <dd class="mt-1 text-sm text-gray-600 sm:mt-0 sm:col-span-2">
          <%= @billing_report.start %>
        </dd>
      </div>

      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">End Date/Time</dt>
        <dd class="mt-1 text-sm text-gray-600 sm:mt-0 sm:col-span-2">
          <%= @billing_report.end %>
        </dd>
      </div>

      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Billable Hours</dt>
        <dd class="mt-1 text-sm text-gray-600 sm:mt-0 sm:col-span-2">
          <%= @billing_report.node_hours %>
        </dd>
      </div>

      <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">Created</dt>
        <dd class="mt-1 text-sm text-gray-600 sm:mt-0 sm:col-span-2">
          <%= @billing_report.inserted_at %>
        </dd>
      </div>
    </dl>
  </div>
</div>

<div class="mt-4">
  <h2 class="text-lg font-medium text-gray-500">Chart</h2>

  <div class="mt-2">
    <%= live_component @socket, HomeBaseWeb.BillingReportLive.ChartComponent, id: :main_chart, data: @billing_report.by_hour %>
  </div>
</div>

<div class="mt-4">
  <h2 class="text-lg font-medium text-gray-500">Usage Reports</h2>
  <table class="min-w-full divide-y divide-gray-300">
    <thead class="bg-gray-200">
      <tr>
        <th
          class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
        >
          id
        </th>
        <th
          class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
        >
          Number of Nodes
        </th>
        <th
          class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
        >
          Number of Pods
        </th>
        <th
          class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
        >
          Generated At
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody id="usage_reports">
      <%= for usage_report <- @billing_report.usage_reports do %>
        <tr id="usage_report-<%= usage_report.id %>">
          <td
            class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"
          >
            <%= usage_report.id %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
            <%= usage_report.num_nodes %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
            <%= usage_report.num_pods %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
            <%= usage_report.generated_at %>
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
            <span><%= live_redirect "Show", to: Routes.usage_report_show_path(@socket, :show, usage_report) %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<span><%= live_redirect "Back", to: Routes.billing_report_index_path(@socket, :index) %></span>